### ISSUE TITLE
Issue on inherited Parameters for embedded flows

### ISSUE THREAD

**Issue by armisael** [azkaban/azkaban#1522]
Let's say we have a common job that is used by two embedded flows, which simply set some parameters when running it. Let's also say that such parameters are also used by other jobs, and therefore must placed inside a `.properties` file to avoid duplication.

[This project](https://github.com/azkaban/azkaban/files/1348950/_project.zip) shows an example of this:

```
.
|____common                    // folder for the common jobs
| |____echo.job                // common job, it requires a `foo` parameter
|____flow-a
| |____default.properties      // contains `foo.value=hello world`
| |____do-echo-a.job           // embedding of echo.job: it sets `foo=${foo.value}`
|____flow-b
| |____default.properties      // contains `foo.value=foo bar`
| |____do-echo-b.job           // embedding of echo.job: it sets `foo=${foo.value}`
|____main.job
```

This structure is allowed on azkaban 2.5: when `do-echo-a.job` is run, the parameter is expanded, and `foo=hello world` will be used when executing `echo.job`. Similarly, when `do-echo-b.job` is run, `foo=foo bar` will be used when executing `echo.job`.

In azkaban 3.x this is not allowed anymore. Expansion of parameters in the `do-echo-*.job` is performed based on the location of `echo.job`, and not of the flow itself; when `foo` is expanded, then, the property `foo.value` is searched among the properties define at `common` folder level, even if they are defined on a `.job` file in `flow-a` or `flow-b`.

Is this behaviour intended?

**Comment by HappyRay** [comment]
How does do-echo-a.job reference echo.job?

**Comment by armisael** [comment]
As an embedded flow:
```type=flow
flow.name=echo

foo=${foo.value}```

You can download the project and give it a try, it's linked in the issue description.

**Comment by jamiesjc** [comment]
@armisael @HappyRay This issue could be related to an old PR https://github.com/azkaban/azkaban/commit/d114439dbc1f5d7f948888f7240e9a92a7cc1661.
In azkaban.execapp.FlowRunner#prepareJobProperties,
only if a node is not an instance of ExecutableFlow, it will load the sharedProps for the node. In this scenario, the sharedProps are defined in the default.properties files and they are not populated into the node since it is an instance of ExecutableFlow, and thus fail to be resolved in azkaban.utils.PropsUtils#resolveProps, causing the failure.
I tried removing `if (!(node instanceof ExecutableFlowBase))` and the flow could run successfully. This might not be the ideal fix, but it points out where the issue locates.

**Comment by armisael** [comment]
Thank you for looking into it!

Do we know the rationale behind that PR? By reading #226 it doesn't seem like we had a real use-case in mind, it made sense to implement it that way, maybe because this idea of overriding parameters in different flows was not considered.

Does removing that condition break any test?

**Comment by armisael** [comment]
If you don't mind, we might try to spend some time on this and test your solution.

**Comment by jamiesjc** [comment]
@armisael Sure, you can go ahead and investigate on the solution. I might not have enough bandwidth to work on this issue, but I'll definitely review your change and provide feedback.

**Comment by armisael** [comment]
@jamiesjc let me know if something is not clear, thanks!
