### ISSUE TITLE
flow schedule ,one time cron expression result repeatable run every minitue

### ISSUE THREAD

**Issue by liweigong** [azkaban/azkaban#1529]
azkaban version 3.12.0,  Not solo mode.

we schedule a flow to run one time at 2017-10-11 10:50:00
and after the Execution . the flow still rerun every minute after that.

here is the screenshot :

the scheduling

![_20171011104442](https://user-images.githubusercontent.com/7710640/31420346-883c563e-ae73-11e7-9341-347261ed343c.png)

the executions:

![_20171011105744](https://user-images.githubusercontent.com/7710640/31420347-8bad71a4-ae73-11e7-8bec-88995b27a25e.png)

**Comment by ameyamk** [comment]
You are running old version - please upgrade to latest one: https://github.com/azkaban/azkaban/releases

**Comment by liweigong** [comment]
may I know which version this bug fixed?  the earlier realease didn't have a note.

**Comment by reallocf** [comment]
Hey @liweigong - I'd suggest jumping up to 3.32.1 which is our latest pre-release (will soon be upgraded to a proper release). 3.34.1 is what we're using in production here at LinkedIn, though we're rolling out 3.36.0 and it's looking like it's free of bugs.

Because 3.12.0 was released in December 2016, I don't know if anybody is knowledgable about the bugs in that particular version. Upgrading should fix the problem (we're not seeing it in production here) and, if not, the current team will be better equipped to help troubleshoot.

Thanks!
