### ISSUE TITLE
azkaban.jobExecutor.utils.process.ProcessFailureException

### ISSUE THREAD

**Issue by encrylife** [azkaban/azkaban#1566]
command file:
type=javaprocess
java.class=AzkabanExample
working.dir=/home/ubuntu/Downloads/azkaban/azkaban-exec-server/job
but it not work
logs:
18-11-2017 22:23:44 CST command INFO - Starting job command at 1511015024964
18-11-2017 22:23:44 CST command INFO - azkaban.webserver.url property was not set
18-11-2017 22:23:44 CST command INFO - job JVM args: -Dazkaban.flowid=command -Dazkaban.execid=31 -Dazkaban.jobid=command
18-11-2017 22:23:44 CST command INFO - Building javaprocess job executor. 
18-11-2017 22:23:45 CST command INFO - No classpath specified. Trying to load classes from /home/ubuntu/Downloads/azkaban/azkaban-exec-server/job
18-11-2017 22:23:45 CST command INFO - 1 commands to execute.
18-11-2017 22:23:45 CST command INFO - cwd=/home/ubuntu/Downloads/azkaban/azkaban-exec-server/job
18-11-2017 22:23:45 CST command INFO - effective user is: test
18-11-2017 22:23:45 CST command INFO - Command: java -Dazkaban.flowid=command -Dazkaban.execid=31 -Dazkaban.jobid=command -Xms64M -Xmx256M -cp  AzkabanExample 
18-11-2017 22:23:45 CST command INFO - Environment variables: {JOB_OUTPUT_PROP_FILE=/home/ubuntu/Downloads/azkaban/azkaban-exec-server/job/command_output_3561948938160028661_tmp, JOB_PROP_FILE=/home/ubuntu/Downloads/azkaban/azkaban-exec-server/job/command_props_6040937614697965721_tmp, KRB5CCNAME=/tmp/krb5cc__ttt__command__command__31__test, JOB_NAME=command}
18-11-2017 22:23:45 CST command INFO - Working directory: /home/ubuntu/Downloads/azkaban/azkaban-exec-server/job
what happen?
I copy the 
 java -Dazkaban.flowid=command -Dazkaban.execid=31 -Dazkaban.jobid=command -Xms64M -Xmx256M -cp  AzkabanExample to commandline  it still failed,but if I remove -cp arg it work well.
what's wrong? command file error?

**Comment by juhoautio** [comment]
It seems like maybe you have the job property `classpath` defined with an empty value? If yes, delete that property, and Azkaban shouldn't be trying to add `-cp` without following args any more.

Any way this seems like a bug to me; Azkaban should check mroe carefully if the list for `-cp`  is empty and not add it in that case.

**Comment by juhoautio** [comment]
Hmm and did you include some.jar (that contains the class `AzkabanExample`) in the same folder as your .job file is in the zip?

**Comment by juhoautio** [comment]
Maybe some of these [new test cases in JavaProcessJobTest.java](https://github.com/azkaban/azkaban/pull/1567/files#diff-f31da6202e0d71971caa4d1991b87a54) match with yours.

**Comment by encrylife** [comment]
I search the source code,I find it will add the -cp XXX as you mention above,  I add the class name after the command ,it work well ,so I add  jvm.args  AzkabanExample.when I add classpath it report failed again.I hava no idea ,can you help me? the command file:

working.dir = /home/ubuntu/Downloads/azkaban/azkaban-exec-server/job
classpath =fastjson-1.2.38.jar,springBootBaseService-1.0-SNAPSHOT.jar,springBootBaseService_fat.jar
jvm.args =AzkabanExample
type =javaprocess
java.class =AzkabanExample
the error log:
Exception in thread "main" java.lang.NoClassDefFoundError: com/front/baseService/entity/ESORequest
.In the command line ,I delete the arg -D it work well in the command line as  java -cp .:fastjson-1.2.38.jar:springBootBaseService-1.0-SNAPSHOT.jar:springBootBaseService_fat.jar  AzkabanExample.You can reproduce the bug.

**Comment by encrylife** [comment]
I had resolved the problem,via the error log,finally I modified command job file  as 

working.dir=/home/ubuntu/Downloads/azkaban/azkaban-exec-server/job
classpath=.:fastjson-1.2.38.jar,springBootBaseService-1.0-SNAPSHOT.jar,springBootBaseService_fat.jar
type= javaprocess
java.class= AzkabanExample.
 Thank you prompt reply !

**Comment by nimuyuhan** [comment]
I have the same problem. I find that logs ‘No classpath specified’.
logs:
15-10-2018 21:26:21 CST hive-demo INFO - Error: A JNI error has occurred, please check your installation and try again
15-10-2018 21:26:21 CST hive-demo INFO - Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.Class.getDeclaredMethods0(Native Method)
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.Class.getMethod0(Class.java:3018)
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.Class.getMethod(Class.java:1784)
15-10-2018 21:26:21 CST hive-demo INFO - 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
15-10-2018 21:26:21 CST hive-demo INFO - 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
15-10-2018 21:26:21 CST hive-demo INFO - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
15-10-2018 21:26:21 CST hive-demo INFO - 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
15-10-2018 21:26:21 CST hive-demo INFO - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
15-10-2018 21:26:21 CST hive-demo INFO - 	... 7 more
15-10-2018 21:26:21 CST hive-demo INFO - Process completed unsuccessfully in 0 seconds.
15-10-2018 21:26:21 CST hive-demo ERROR - caught error running the job
15-10-2018 21:26:21 CST hive-demo ERROR - Job run failed!
java.lang.Exception: java.lang.RuntimeException: azkaban.jobExecutor.utils.process.ProcessFailureException
	at azkaban.jobtype.HadoopHiveJob.run(HadoopHiveJob.java:110)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:784)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:600)
	at azkaban.execapp.JobRunner.run(JobRunner.java:561)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: azkaban.jobExecutor.utils.process.ProcessFailureException
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:304)
	at azkaban.jobtype.HadoopHiveJob.run(HadoopHiveJob.java:106)
	... 8 more
Caused by: azkaban.jobExecutor.utils.process.ProcessFailureException
	at azkaban.jobExecutor.utils.process.AzkabanProcess.run(AzkabanProcess.java:130)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:296)
	... 9 more

**Comment by juhoautio** [comment]
Repo owners, could you consider this, please:

https://github.com/azkaban/azkaban/pull/1567
