### ISSUE TITLE
job callback does not parse multiple variables

### ISSUE THREAD

**Issue by badbye** [azkaban/azkaban#1593]
Here is my configuration:
```
job.notification.failure.1.body={"title": "?{job}:?{status}", "mailto": "xxx", "msg": "?{server}:?{project}:?{flow}:?{executionId}:?{job}:?{status}"})
```
The `?{job}` and the `?{status}` arguments are used twice. However, according to the log, not all the arguments are parsed: 
```
27-12-2017 13:37:21 CST test_mail INFO - postActualBody: {"title": "test_mail:failed", "mailto": "xxx", "msg": "WorkstationSelene:datascience:test_mail:59:?{job}:?{status}"})
```

BTW, it will be fancy if the environment variables can also be used in the callback function.

**Comment by juhoautio** [comment]
Yes, it only replaces the first occurrence, as you can see in the code here:
https://github.com/azkaban/azkaban/blob/master/azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackUtil.java#L274-L300

I don't see why it should be like that. Hence, our internal Azkaban fork uses `replaceAll` instead of `replaceFirst`.

**Comment by badbye** [comment]
Thanks for your reply. At least I know how to change it if I really want to replace all of them.
