### ISSUE TITLE
Don't understand azkaban execution environment

### ISSUE THREAD

**Issue by trentgerman** [azkaban/azkaban#1723]
Why does this job fail? 
![image](https://user-images.githubusercontent.com/36200193/38440775-14413e6e-39a8-11e8-860e-e8045c57deab.png)

![image](https://user-images.githubusercontent.com/36200193/38440818-36480a38-39a8-11e8-83ba-0bb5c801853f.png)
But jobs with command `echo hello` work perfectly fine? Does azkaban not execute in the standard BASH shell?

**Comment by xunnanxu** [comment]
@trentgerman I think it depends on how you configure your job. You might want to share your .job file. The context here is not enough.

**Comment by xunnanxu** [comment]
Actually I think it has something to do with your command.
I guess you just literally put `command=cd whatever...`.
To understand why this fails, you need some background knowledge:
1. Azkaban basically just uses java `ProcessBuilder` to invoke an external binary.
2. The command must invoke an executable file. When you run `echo`, it actually invokes `/bin/echo` in a typical linux based system.
3. `cd` is not an executable. It's a shell built-in command. There's no `/bin/cd`, which is why this fails.
4. On the contrary, `echo` is a bit special as it has two versions in a general shell (e.g. bash) - a shell built-in command and a `/bin/echo` executable. When you invoke `echo` in bash, you actually run the built-in command (`which echo`) whereas the same command invokes `/bin/echo` when used in java. However, not all shells are guaranteed to have `echo` as a built-in command.

If you want this to work, you can use `bash -c 'ur cmd'` for the reason above.

**Comment by trentgerman** [comment]
@xunnanxu thank you! That was a clear, concise answer. Now I understand the error azkaban was showing. Is there any documentation on `ProcessBuilder`?

**Comment by HappyRay** [comment]
@xunnanxu Thanks for answering user questions.

@trentgerman in case you are not aware yet
in
https://github.com/azkaban/azkaban/blob/master/README.md
https://github.com/azkaban/azkaban/blob/master/CONTRIBUTING.md
>  Please don't report an issue as a way to ask a question. Use the Google group instead.

**Comment by HappyRay** [comment]
It's fair to open an issue that you find the documentation needs an improvement. PRs for docs are welcome.
