### ISSUE TITLE
Build on trunk has failed

### ISSUE THREAD

**Issue by HappyRay** [azkaban/azkaban#1956]
see

https://travis-ci.org/azkaban/azkaban/builds

https://travis-ci.org/azkaban/azkaban/builds/428855477?utm_source=email&utm_medium=notification

**Comment by kunkun-tang** [comment]
No failure is identified in our local build.

```
# latang at latang-mn2.linkedin.biz in ~/LNKDRepos/azkaban/az-core on git:master ●
→ ../gradlew clean compileJava
Parallel execution with configuration on demand is an incubating feature.

> Task :az-core:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by HappyRay** [comment]
@li-ygerchikov @kunkun-tang Thanks for looking into this.

**Comment by li-ygerchikov** [comment]
Traced failures to a corrupt build cache, likely due to Travis infra hiccup / intermittent connectivity issue. Deleted and rebuilt cache, verified that builds are passing. Restarted failed builds.
Not sure what we can do to prevent this in the future, or to recover automatically. May need some extra thought if we never want to see this type of failure again.

**Comment by HappyRay** [comment]
@li-ygerchikov Thanks!
Could you share how you fixed the cache for future reference?

**Comment by tpensyl** [comment]
@HappyRay I just hit this issue today. Fixed it by cleared the cache using answers here https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache
