### ISSUE TITLE
Azkaban Logout Time Period

### ISSUE THREAD

**Issue by rajivchodisetti** [azkaban/azkaban#433]
HI Team ,

We have been using azkaban from past 6 months and the only problem that we are facing as of now is , once we login through the azkaban UI , there is no way we can save the username and password and also session is getting logged out every 5 or 10 minutes and is very irritating some times . 

Have checked the documentation but couldn't find any variable through which I can set the session timeout value .

Please help us in resolving the same

**Comment by joeharris76** [comment]
The login lasts 24 hours as long as you're on the same connection. I'd suggest that you use a tool like LastPass to make user/pass entry quicker.

**Comment by shahneil88** [comment]
Can we set the session timeout manually? I do not want it to logout every 24 hours

**Comment by shahneil88** [comment]
I found a variable called SESSION_TIME_TO_LIVE and it is declared as final in
azkaban-common/src/main/java/azkaban/server/session/SessionCache.java

**Comment by darrenfu** [comment]
Looks like it resolves my same issue when set SESSION_TIME_TO_LIVE to a longer time (2 days).

**Comment by duke2012** [comment]
meet same problem in docker

**Comment by li-afaris** [comment]
Hi @duke2012, this is a very old issue to be updating.  Something to remember is the session ids are stored in memory on the webserver.  If you restart the docker container or the webserver process on a physical machine, the session ids will get lost.   

Secondly, if you search `session.time.to.live` on the [documentation site](http://azkaban.github.io/azkaban/docs/latest/), you'll find the timeout is controlled with a configuration setting.  The default should be 24 hours.  

If this information doesn't resolve your question, please open a new issue that describes your environment and what the problem is.   Thanks.
