### ISSUE TITLE
When is Azkaban 3.0 going to be released?

### ISSUE THREAD

**Issue by vikramkone** [azkaban/azkaban#544]
Any ETA/timelines to set the expectations for our team ?

**Comment by davidzchen** [comment]
IIRC the remaining blocker for 3.0 is finishing the testing and merging in the changes for multiple executors.

@hluu - Is there an updated ETA on the 3.0 release?

**Comment by vikramkone** [comment]
ping?

**Comment by davidzchen** [comment]
@hluu - Is there an updated ETA for 3.0?

**Comment by devangorder** [comment]
My team is also very interested in the Azkaban 3.0 release with support for multiple executors. Am I correct in that I should wait for it to come out, rather than downloading and building one of the branches available currently? I'm a little confused which is the one to go off of currently, between master, multipleexecutors, multipleexecutory_canary, release 3.0...

**Comment by hluu** [comment]
Let me get back to you shortly about the Azkaban 3.0 release.

**Comment by devangorder** [comment]
bump?

**Comment by vikramkone** [comment]
ping?

**Comment by hluu** [comment]
The merging of the multi-executor branch to main trunk has started and I
think in a week or two, we should have Azkaban 3.0.

Thanks for your interest in Azkaban 3.0.

Hien

**Comment by zleswomp** [comment]
3.0 still looks missing from the downloads page.  Any update timeline here?

**Comment by ameyamk** [comment]
We are now on 3.20 - soon releasing 4.0. Closing.
