### ISSUE TITLE
azkaban-execserver:createVersionFile FAILED

### ISSUE THREAD

**Issue by hhservice** [azkaban/azkaban#581]
when builde azkaban 3.0 ，occur azkaban-execserver:createVersionFile FAILED

**Comment by logiclord** [comment]
can you please run tests in debug mode and share stacktrace ?

**Comment by hhservice** [comment]
i want to builde azkaban-3.0.0 with src, but found error . so i don't know what's run tests in debug ?
but when i debug used source code in the ide, this error not found, but found other error, in the JdbcExecutorLoader , shoud be exec_id  not execution_id in some where.

**Comment by Kindaichi** [comment]
I have the same problem, and I had solve it.
you can add --info when running gradlew

The problem is the build process would use git command when create version file,but if you download the  tarball from https://github.com/azkaban/azkaban/archive/3.0.0.tar.gz, it is not  a git repo, so git would exit with non-zero value.

To solve this, all you need to do is git clone the azkaban repo, and checkout to the 3.0.0 tag.

**Comment by hhservice** [comment]
thanks
